### PR TITLE
fix(docs): remove remote fetching of merge-confidence.md

### PR DESCRIPTION
**Pull request by Gabriel-Ladzaretti**
## Changes:
merge confidence related markdown file should be now internal and shouldn't be remotely fetched.

## Context:
- https://github.com/renovatebot/renovate/issues/22891#issuecomment-1603884537

### CODE REVIEW

**Comment by rarkins** [comment]
@Gabriel-Ladzaretti do you mean the readme will be added to the main renovate repo, or this one, or have I misunderstood? Also I'm confused why we'd remove it from here before adding it back somewhere else

**Comment by rarkins** [comment]
Blocked by https://github.com/renovatebot/renovate/pull/23215

**Comment by HonkingGoose** [comment]
> Blocked by https://github.com/renovatebot/renovate/pull/23215

And also blocked by us pulling in the new Git submodule update that has the commit from the PR in it. Or this repository won't have any Merge Confidence source files at all for a short while. 😉

**Comment by HonkingGoose** [comment]
@Gabriel-Ladzaretti You should sync your branch with the `main` branch, the docs changes have been pulled in by Renovate.

**Review by rarkins — APPROVED** [review]

**Pull request merged**
