### PR TITLE
chore: add google site verification

### LINKED ISSUE #216: Add site to Google search console
### What would you like to be able to do?

Gain visibility into visitors to docs.renovatebot.com

### Did you already have any implementation ideas?

We can choose one of these:

### Meta tag in root index file

```
<meta name="google-site-verification" content="DsI--mVG-3CMn_nlFbzI5pdPiefn3muBQgEYpr36C1s" />
```

### Upload HTML file

We can add an empty file called `googleb17844ca8e94dda1.html` to the site

### Do you want to write this feature yourself?

Maybe

### PR DESCRIPTION
**Pull request by rarkins**
## Changes:

Adds empty html file to site for google site verification

## Context:

Closes #216

### CODE REVIEW

**Comment by rarkins** [comment]
@viceice do you know if the entire contents of `src` are copied automatically?

**Review by bgoonz — APPROVED** [review]

**Review by bgoonz — APPROVED** [review]
Approved

**Review by viceice — APPROVED** [review]

**Comment by viceice** [comment]
> @viceice do you know if the entire contents of `src` are copied automatically?

yes, i think so

**Comment by viceice** [comment]
will fix the prettier issue now

**Pull request merged**
