### PR TITLE
chore: recommended link check strictness

### LINKED ISSUE #304: Try MkDocs `v1.5.0` link validation
### Describe the proposed change(s).

The new MkDocs `1.5.0` version comes with better link validation. [^1] We'll first need to update to that version, and then I can try updating the config file, and test the site build.

[^1]: [MkDocs `1.5.0` changelog, expanded validation of links](https://www.mkdocs.org/about/release-notes/#expanded-validation-of-links)

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- Use MkDocs maintainer's recommended strictness for link checking

## Context:

Quote from the MkDocs manual on validation: [^1]

> Recommended settings for most sites (maximal strictness)
> 
> ```yaml
> validation:
>   omitted_files: warn
>   absolute_links: warn
>   unrecognized_links: warn
> ```

Now we "only" need to fix:

```
Aborted with 457 warnings in strict mode!
```

🙃 

Closes #304 

[^1]: https://www.mkdocs.org/user-guide/configuration/#validation

### CODE REVIEW

**Review by viceice — APPROVED** [review]

**Comment by HonkingGoose** [comment]
@viceice You did see that we have `457 warnings` in the build now? 😉 Or do you want to merge the broken tests, and then gradually fix up the Renovate docs generation code?

**Comment by viceice** [comment]
no, we should fix them before merge

**Comment by HonkingGoose** [comment]
I think we can get rid of the bulk of the warnings by fixing this type of warning in the docs generating code:

`WARNING -  Doc file 'index.md' contains an unrecognized relative link './modules/platform/github/', it was left as is. Did you mean 'modules/platform/github/index.md'?`

**Comment by viceice** [comment]
I'm thinking on doing some more validation on renovate repo.

@rarkins WDYT to move docs generation to the main repo? so we use a workflow there to push the GitHub pages?

**Comment by viceice** [comment]
nope, we can only build there, but publish needs to be done here.

so we should only move the generation

**Comment by HonkingGoose** [comment]
@viceice did you make an issue to track your "move docs generation to main repository" idea? Did you already start work on this idea maybe?

**Comment by viceice** [comment]
please create an issue for me in main repo. will hopefully start soon

**Comment by viceice** [comment]
a lot of the errors are fixed, we need to wait for bubble through 🙃 
- https://github.com/renovatebot/renovate/pull/25683

**Comment by viceice** [comment]
another wave of fixes
- https://github.com/renovatebot/renovate/pull/25686

**Comment by viceice** [comment]
Opened a discussion for the remaining warning
- https://github.com/squidfunk/mkdocs-material/discussions/6318

**Comment by HonkingGoose** [comment]
I see we're down to a _single_ warning. We started with 457 warnings. You're making good progress! :smile:

**Comment by viceice** [comment]
- https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/92

**Pull request merged**
